### ISSUE TITLE
Video Rendering Issues

### ISSUE THREAD

**Issue by reckoner165** [slawrence/simple-360-player#2]
I tried replacing the sample video link with my own. This repeatedly throws a Non-power-of-2 texture render warning in chrome and goes on to never load the video. 

The same warning also appears with the default video but stops at some point. Usually after ~40 times.

Here's the error:
`[.Offscreen-For-WebGL-0x7fa441a00200]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.`

**Comment by slawrence** [comment]
The warnings show before video load (i.e. the texture is bound to the video before it has loaded - which is not renderable). I'm guessing your first video never loads hence why you repeatedly get the warning. Try loading the same video in just a video element to see if it loads there.

The default video works eventually but takes a little while to load. I get a few warnings before it finally stops too.

I can get rid of the warnings by only assigning the texture after video load but that in itself probably won't solve your video loading problems (i.e. the warnings are annoying but aren't directly causing nothing to render/load). Make sure your video format is supported by whatever browser you're using.
