### ISSUE TITLE
The video is mirrored and zoomed

### ISSUE THREAD

**Issue by ghost** [slawrence/simple-360-player#3]
HI @slawrence ,

Is there a way to view the camera from further away, currently my video is working but is zoomed in too much and the video is mirrored for some reason.

can you help?

**Comment by slawrence** [comment]
Hi @ghost - sorry for the late reply. A recent commit should fix the mirror issue. Zooming can be adjusted by messing with the last two arguments of this function: https://github.com/slawrence/simple-360-player/blob/master/src/simple-360.js#L174

Wouldn't be a bad idea to add a couple options for this so custom values can be passed in when the player is initialized.
